### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error: Not Found

### ISSUE THREAD

**Issue by syphoxy** [lukapusic/soundcloud-dl#108]
tried to download my likes from my account. doesn't seem to work anymore.

```
SoundCloud % scdl -f -l http://soundcloud.com/syphoxy
Soundcloud Downloader
Downloading to /home/spyroboy/Music/SoundCloud...

Found an user profile

Favorite n°1
Downloading SPINEE - FUTURE FAST MOVING ROYAL DOG
100% [........................................................................] 11601710 / 11601710
Settings tags...

SPINEE - FUTURE FAST MOVING ROYAL DOG.mp3 Downloaded.


Favorite n°2
Traceback (most recent call last):
  File "/usr/bin/scdl", line 9, in <module>
    load_entry_point('scdl==v1.0.6', 'console_scripts', 'scdl')()
  File "/usr/lib/python3.3/site-packages/scdl/scdl.py", line 87, in main
    parse_url(arguments["-l"])
  File "/usr/lib/python3.3/site-packages/scdl/scdl.py", line 155, in parse_url
    download_user_favorites(item)
  File "/usr/lib/python3.3/site-packages/scdl/scdl.py", line 261, in download_user_favorites
    download_track(track)
  File "/usr/lib/python3.3/site-packages/scdl/scdl.py", line 297, in download_track
    stream_url = client.get(track.stream_url, allow_redirects=False)
  File "/usr/lib/python3.3/site-packages/soundcloud/client.py", line 130, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/lib/python3.3/site-packages/soundcloud/request.py", line 135, in make_request
    result.raise_for_status()
  File "/usr/lib/python3.3/site-packages/requests/models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found
SoundCloud %
```
```
SoundCloud % uname -a
Linux localhost.localdomain 3.18.7-100.fc20.x86_64 #1 SMP Wed Feb 11 19:01:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
SoundCloud % python --version
Python 2.7.5
```

let me know if you need to know anything else

**Comment by syphoxy** [comment]
disregard. I forgot to update! sorry!
